# Schema for OCI Resource Manager Private Terraform Template
title: "My Test OCI Stack"
description: "This stack creates a VCN, subnet, compute instance, and block volume."
schemaVersion: 1.1.0
version: "1"
locale: "en"

variableGroups:
  - title: General Configuration
    visible: true
    variables:
      - region
      - compartment_id
  - title: Computer Instance Variable Group
    visible: true
    variables:
      - instance_name_prefix
#      - instance_ad
      - instance_shape
      - instance_image_id
      - instance_count
      - instance_ssh_public_key
      - instance_ocpu
      - instance_mem_in_gbs
      - instance_has_sec_vol
      - instance_secvol_in_gbs
      - instance_secvol_vpus_per_gb
      - instance_boot_volume_size_in_gbs
      - instance_boot_volume_vpus_per_gb
  - title: VCN Variable Group
    visible: true
    variables:
      - instance_vnic_create_vnic_details
      - instance_vcn_id
      - instance_subnet_id

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created.
    required: true
  compartment_id:
    type: oci:identity:compartment:id
    title: Instance Compartment Name
    description: The name of the compartment where compute instance will be created.
    required: true
#  instance_ad:
#    type: oci:identity:availabilitydomain:name
#    dependsOn:
#      compartmentId: compartment_id
#    required: true
  instance_name_prefix:
    type: string
    title: "Prefix for instance names."
    required: true
    description: "Instance names which will be appended with index."
    default: "MyInstance"
  instance_shape:
    type: oci:core:instanceshape:name
    title: "Compute Shape"
    default: "VM.Standard.A1.Flex"
    required: true
    dependsOn: 
      compartmentId: compartment_id
  instance_image_id:
    type: oci:core:image:id
    title: "Image ID"
    description: "Compute Image"
    required: true
    dependsOn:
      compartmentId: compartment_id
      shape: instance_shape
  instance_count:
    type: integer
    title: "Number of Instance to Deploy"
    description: Number of Nodes
    required: true
  instance_ssh_public_key:
    title: SSH public key
    description: Public SSH key to be included in the ~/.ssh/authorized_keys file for the default user on the instance
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    additionalProps:
      allowMultiple: true
    required: true
    default: [""]
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
  instance_ocpu:
    type: integer
    title: "OCPU amount for instances."
    description: Number of OCPU allocated for this shape.
    required: true
  instance_mem_in_gbs:
    type: integer
    title: "Memory amount for instances."
    description: Amount of memory allocated for this shape.
    required: true
  instance_has_sec_vol:
    type: boolean
    title: "Second volumn switch."
    description: Specify when you need the second volumn.
    required: true
    default: false
  instance_secvol_in_gbs:
    type: integer
    title: "Second volumn size."
    description: Volumn size of second volumn.
    required: true
  instance_secvol_vpus_per_gb:
    type: integer
    title: "Vpus per GB for second volumn"
    description: Vpus per GB for the second volumn.
    required: true
  instance_boot_volume_size_in_gbs:
    type: integer
    title: "Boot Volumn Size in GB."
    description: Boot volumn size in GB.
    required: true
  instance_boot_volume_vpus_per_gb:
    type: integer
    title: "Boot Volumn VPUS / GB"
    description: Boot volumn VPUS per GB.
    required: true
  instance_vnic_create_vnic_details:
    type: boolean
    title: "Select when creating public IP in a public subnet"
    description: Availability to Internet.
    required: true
  instance_vcn_id: 
    type: oci:core:vcn:id
    title: "VCN of the compute instances."
    description: VCN where the instances are to be deployed.
    required: true
    dependsOn: 
      compartmentId: compartment_id
  instance_subnet_id:
    type: oci:core:subnet:id
    title: "Subnet of the compute instances"
    description: Subnet where the instances are to be deployed.
    required: true
    dependsOn: 
      compartmentId: compartment_id
      vcnId: instance_vcn_id
