# Schema for OCI Resource Manager Private Terraform Template
title: "My Test OCI Stack"
description: "This stack creates a VCN, subnet, compute instance, and block volume."
schemaVersion: 1.1.0
version: "1"
locale: "en"

variableGroups:
  - title: General Configuration
    visible: true
    variables:
      - region
      - compartment_id
  - title: Computer Instance Variable Group
    visible: true
    variables:
      - instance_ad
      - instance_shape
      - instance_image_id
      - instance_count
      - instance_ocpu
      - instance_mem_in_gbs
      - instance_secvol_in_gbs
      - instance_secvol_vpus_per_gb
      - instance_boot_volume_size_in_gbs
      - instance_boot_volume_vpus_per_gb
  - title: VCN Variable Group
    visible: true
    variables:
      - vcn_dns_label
      - vcn_display_name
      - vcn_cidr_block
      - subnet_public_access
      - subnet_dns_label
      - subnet_display_name
      - subnet_cidr_block

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created.
    required: true
  compartment_id:
    type: oci:identity:compartment:id
    title: Instance Compartment Name
    description: The name of the compartment where compute instance will be created.
    required: true
  instance_ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compartment_id
    required: true
  instance_shape:
    type: oci:core:instanceshape:name
    title: "Compute Shape"
    default: "VM.Standard.A1.Flex"
    required: true
    dependsOn: 
      compartmentId: compartment_id
  instance_image_id:
    type: oci:core:image:id
    title: "Image ID"
    description: "Compute Image"
    required: true
    dependsOn:
      compartmentId: compartment_id
      shape: instance_shape
  instance_count:
    type: integer
    title: "Number of Instance to Deploy"
    description: Number of Nodes
    required: true
  instance_ocpu:
    type: integer
    title: "OCPU amount for instances."
    description: Number of OCPU allocated for this shape.
    required: true
  instance_mem_in_gbs:
    type: integer
    title: "Memory amount for instances."
    description: Amount of memory allocated for this shape.
    required: true
  instance_secvol_in_gbs:
    type: integer
    title: "Second volumn size."
    description: Volumn size of second volumn.
    required: true
  instance_secvol_vpus_per_gb:
    type: integer
    title: "Vpus per GB for second volumn"
    description: Vpus per GB for the second volumn.
    required: true
  instance_boot_volume_size_in_gbs:
    type: integer
    title: "Boot Volumn Size in GB."
    description: Boot volumn size in GB.
    required: true
  instance_boot_volume_vpus_per_gb:
    type: integer
    title: "Boot Volumn VPUS / GB"
    description: Boot volumn VPUS per GB.
    required: true
  vcn_dns_label:
    type: string
    required: true
    title: "VCN DNS Label"
    description: "The label string of VCN DNS name."
  vcn_display_name:
    type: string
    required: true
    title: "VCN Display Name"
    description: "The display name of the VCN."
  vcn_cidr_block:
    type: string
    required: true
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    title: "VCN CIDR Block"
    description: "CIDR block of the VCN"
  subnet_public_access:
    type: boolean
    default: false
    required: true
    title: "Subnet Access"
    description: "Select when creating public subnet."
  subnet_dns_label:
    type: string
    required: true
    title: "Subnet DNS Label"
    description: "The label string of subnet name."
  subnet_display_name:
    type: string
    required: true
    title: "Subnet Display Name"
    description: "The display name of the subnet."
  subnet_cidr_block:
    type: string
    required: true
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    title: "Subnet CIDR Block"
    description: "CIDR block of the subnet"
